#+TITLE: Authpages

A demonstration of the usual signup, forget password, reset password and confirm
pages associated with user authentication management, implemented without a
traditional server buth instead with couchdb and server side workers ([[http://github.com/michieljoris/cape][cape]]).


* Install of demo 
  Install a CouchDB instance. Make sure that the CouchDB instance is cors
  enabled. (in configuration set to true cors/credentials and httpd/enable_cors
  and set cors/origins/* by clicking 'Add a new section' at the bottom of the
  configuration page and filling in cors, origins and *).

  Clone [[http://github.com/michieljoris/cape][Cape]]. Edit the bottom of the file backend/rean.js to set/edit username,
  password and url of the CouchDB instance.Then cd to the repo's rootfolder and
  execute =node backend/rean.js= This starts the backend workers that connect to
  the CouchDB instance and if necessary initialize it.
  
 This repo contains a [[http://github.com/michieljoris/bb-server][server]] and a [[http://github.com/michieljoris/html-builder][builder]] to quickly setup the demo. Do a =npm
 install= in this repo's root folder and execute =bin/serve= in one terminal and
 a =bin/build= in another folder. Open your browser at [[http://localhost:9001]]. 
 
The various relevant html fragments are in build/html and the relevant
javascript file is in www/scripts/main.js. 
 
 For a description of how it works please see [[http://github.com/michieljoris/cape][Cape]]



